name: Deploy Vite site to GitHub Pages

on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# and to allow turnstyle to read action history.
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read # Required for softprops/turnstyle

# Allow only one concurrent deployment, skipping runs queued between the run in progress and latest queued.
# However, do NOT cancel in-progress runs as we want to let them finish.
concurrency:
  group: "gh-pages-deploy-${{ github.ref }}" # Group by branch
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # ... same steps as before up to build

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Create 404.html for SPA fallback (optional)
        if: success()
        run: cp ./dist/index.html ./dist/404.html

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      # ✅ THROTTLE ONLY IF BUILD SUCCEEDED
      - name: Throttle Deployments (only after successful build)
        if: success() && github.ref == 'refs/heads/main'
        uses: softprops/turnstyle@v1
        with:
          continue-after-seconds: 600
          poll-interval-seconds: 10
          same-branch-only: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        if: success()
        id: deployment
        uses: actions/deploy-pages@v4
